name: base_code_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage: www.msm.com.vn

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  api_response_log:
    git:
      url: https://github.com/taluan/api_response_log.git

  intl: ^0.19.0
  intl_utils: ^2.8.7
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  rxdart: ^0.28.0
  hive: ^2.0.4
  flutter_secure_storage: ^9.2.2
  mobile_device_identifier: ^0.0.2
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  encrypt: ^5.0.1
  number_text_input_formatter: ^1.0.0+8
  flutter_screenutil: ^5.9.1
  keyboard_dismisser: ^3.0.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.0.9
  flutter_image_compress: ^2.4.0
  image: 4.5.3
  http: ^1.3.0
  file_picker: ^9.0.2
  file: ^7.0.0
  image_picker: ^1.0.4
  camera: ^0.11.1
  image_cropper: ^9.0.0
  app_settings: 5.1.1
  diacritic: ^0.1.3
  flutter_cupertino_datetime_picker: ^3.0.0
  syncfusion_flutter_datepicker: ^28.2.4
  cached_network_image: ^3.1.0
  flutter_json_view: ^1.1.4
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.9.0
  flutter_gen: ^5.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Bold.ttf
#          weight: 800
#        - asset: fonts/Roboto-Italic.ttf
#          style: italic
#        - asset: fonts/Roboto-Light.ttf
#          weight: 300
#        - asset: fonts/Roboto-LightItalic.ttf
#        - asset: fonts/Roboto-Medium.ttf
#          weight: 600
#        - asset: fonts/Roboto-Regular.ttf
#          weight: 400
#    - family: Inter
#      fonts:
#        - asset: fonts/Inter-VariableFont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  flutter:
  # Optional
  integrations:
    flutter_svg: true
#    flare_flutter: true

flutter_intl:
  main_locale: vi
  enabled: true

module:
  androidX: true
